# Clean Dockerfile.
FROM ubuntu:22.04

# Minimal secure packages
RUN apt-get update && \
    apt-get install -y --no-install-recommends \
    ca-certificates \
    && apt-get clean && \
    rm -rf /var/lib/apt/lists/*

CMD ["bash"]