name: CI Cloud Security Scanner

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Build Docker image (Vulnerable)
        run: |
          docker build -t demo-app -f Dockerfile.vuln .

      - name: Scan Docker image with Trivy
        uses: aquasecurity/trivy-action@v0.12.0
        with:
          image-ref: demo-app
          format: table
          exit-code: 1
          severity: CRITICAL,HIGH

      - name: Run Cloud Security Scanner (Auto-Remediate)
        run: |
          python main.py --auto-remediate .
