name: Docker Vulnerability Demo

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build vuln image
        run: docker build -f Dockerfile.vuln -t demo-vuln:latest .
      - name: Build clean image
        run: docker build -f Dockerfile.clean -t demo-clean:latest .

      - name: Scan vuln image (should fail)
        id: scan_vuln
        continue-on-error: true
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: demo-vuln:latest
          format: table
          exit-code: 1
          severity: HIGH,CRITICAL

      - name: Scan clean image (should pass)
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: demo-clean:latest
          format: table
          exit-code: 1
          severity: HIGH,CRITICAL

      - name: Fail if vuln image has vulnerabilities
        if: steps.scan_vuln.outcome == 'failure'
        run: |
          echo "Vulnerabilities detected in demo-vuln image. Failing pipeline as expected."
          exit 1
